binary_sensor:
  - platform: template
    sensors:
      be_thermostat_valve:
        friendly_name: 'Термостат спальня'
        value_template: >-
          {{ states('sensor.be_thermostat_position') | int(0) | int > 0 }}
        device_class: lock
        icon_template: >-
          {% if is_state('binary_sensor.be_thermostat_valve', 'on') %}
          mdi:valve-open
          {% else %}
          mdi:valve-closed
          {% endif %}

sensor:
  - platform: template
    sensors:
      be_thermostat_temperature:
        friendly_name: 'Температура на термостате спальня'
        value_template: >-
          {{ state_attr('climate.be_thermostat_climate', 'current_temperature') }}
        icon_template: 'mdi:thermostat'
