homeassistant:
  name: "Дом"
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  elevation: !secret elevation_coord
  unit_system: metric
  time_zone: Europe/Kaliningrad
  packages: !include_dir_named packages

# customize: !include customize.yaml

http:
  server_port: 443
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

lovelace:
  mode: yaml
  resources:
    - url: /local/vacuum-card.js?v=1
      type: module
    - url: /local/lovelace-custom/stack-in-card.js?v=1.0
      type: module
    - url: /local/lovelace-custom/mini-graph-card-bundle.js?v=1.0
      type: module
    - url: /local/lovelace-custom/simple-thermostat.js?v=1.0
      type: module

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Подключение скриптов в папке python_scripts
#python_script:

# Text to speech
tts:
  - platform: google_translate

mqtt:
## Выбрать один из вариантов для брокера
  broker: core-mosquitto  # Локальный брокер
  # broker: IP adress  # Внешний брокер
  discovery: true
  discovery_prefix: homeassistant
  username: mqtt
  password: mqtt

#Вынос во внешние файлы
input_boolean: !include conf.d/input_boolean.yaml
group: !include conf.d/groups.yaml
scene: !include conf.d/scenes.yaml
recorder: !include conf.d/recorder.yaml

input_number: !include conf.d/input_number.yaml
input_select: !include_dir_merge_named conf.d/input-select

#Вынос во внешние папки
timer: !include_dir_merge_named conf.d/timer
sensor: !include_dir_merge_list conf.d/sensor
binary_sensor: !include_dir_merge_list conf.d/bin-sensor
automation: !include_dir_merge_list conf.d/automation
script: !include_dir_merge_named conf.d/script
switch: !include_dir_merge_list conf.d/switch
light: !include_dir_merge_list conf.d/light
climate: !include_dir_merge_list conf.d/climate
