- platform: template
  lights:
    ba_light:
      friendly_name: 'Основной свет в ванной'
      value_template: >-
        {{ is_state('switch.ba_light', 'on') }}
      turn_on:
        - service: switch.turn_on
          entity_id: switch.ba_light
      turn_off:
        - service: switch.turn_off
          entity_id: switch.ba_light
