- platform: template
  lights:
    be_cabinet_light:
      friendly_name: 'Свет в кабинете'
      value_template: >-
        {{ is_state('switch.be_cabinetlight_switch', 'on') }}
      turn_on:
        - service: switch.turn_on
          entity_id: switch.be_cabinetlight_switch
      turn_off:
        - service: switch.turn_off
          entity_id: switch.be_cabinetlight_switch
