- platform: template
  lights:
    be_green_light:
      friendly_name: 'Гирлянда на стене в спальне'
      value_template: >-
        {{ is_state('switch.be_greenlight_switch', 'on') }}
      turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.be_greenlight_switch
      turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.be_greenlight_switch
