- platform: template
  lights:
    be_light:
      friendly_name: 'Свет в спальне'
      value_template: >-
        {{ is_state('switch.be_light_switch_right', 'on') }}
      turn_on:
        - service: switch.turn_on
          entity_id: switch.be_light_switch_right
      turn_off:
        - service: switch.turn_off
          entity_id: switch.be_light_switch_right
