- platform: template
  lights:
    co_light:
      friendly_name: 'Основной свет в коридоре'
      value_template: >-
        {{ is_state('switch.co_light_switch', 'on') }}
      turn_on:
        - service: switch.turn_on
          entity_id: switch.co_light_switch
      turn_off:
        - service: switch.turn_off
          entity_id: switch.co_light_switch
