- platform: template
  lights:
    co_mirror_light:
      friendly_name: 'Подсветка зеркала'
      value_template: >-
        {{ is_state('switch.co_mirror_switch_l2', 'on') }}
      turn_on:
        - service: switch.turn_on
          entity_id: switch.co_mirror_switch_l2
      turn_off:
        - service: switch.turn_off
          entity_id: switch.co_mirror_switch_l2
