- platform: mqtt
  name: co_sls
  availability_topic: 'SLSHubCO/bridge/state'
  command_topic: 'SLSHubCO/led'
  rgb_command_topic: 'SLSHubCO/led'
  rgb_command_template: >-
    {
      "mode": "manual",
      "hex": "#{{ '%02x%02x%02x' | format(red, green, blue) }}"
    }
  on_command_type: 'brightness'
  payload_off: '{"mode": "off"}'
