- platform: template
  lights:
    ha_light:
      friendly_name: 'Основной свет в прихожей'
      value_template: >-
        {{ is_state('switch.ha_light_switch', 'on') }}
      turn_on:
        - service: switch.turn_on
          entity_id: switch.ha_light_switch
      turn_off:
        - service: switch.turn_off
          entity_id: switch.ha_light_switch
