- platform: template
  lights:
    li_light:
      friendly_name: 'Свет в гостиной'
      value_template: >-
        {{ is_state('switch.li_light_switch_left', 'on') }}
      turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.li_light_switch_left
      turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.li_light_switch_left
