- platform: template
  lights:
    lo_light:
      friendly_name: 'Основной свет на лоджии'
      value_template: >-
        {{ is_state('switch.lo_light_switch', 'on') }}
      turn_on:
        - service: switch.turn_on
          entity_id: switch.lo_light_switch
      turn_off:
        - service: switch.turn_off
          entity_id: switch.lo_light_switch
