- platform: template
  lights:
    to_light:
      friendly_name: 'Основной свет в туалете'
      value_template: >-
        {{ is_state('switch.to_light_switch', 'on') }}
      turn_on:
        - service: switch.turn_on
          entity_id: switch.to_light_switch
      turn_off:
        - service: switch.turn_off
          entity_id: switch.to_light_switch
