- platform: template
  sensors:
    be_thermostat_valve:
      friendly_name: 'Термостат спальня'
      value_template: >-
        {{ states('sensor.be_thermostat_position') | int > 0 }}
      device_class: lock
      icon_template: >-
        {% if is_state('binary_sensor.be_thermostat_valve', 'on') %}
        mdi:valve-open
        {% else %}
        mdi:valve-closed
        {% endif %}
