- platform: template
  sensors:
    ch_thermostat_valve:
      friendly_name: 'Термостат детская'
      value_template: >-
        {{ states('sensor.ch_thermostat_position') | int > 0 }}
      device_class: lock
      icon_template: >-
        {% if is_state('binary_sensor.ch_thermostat_valve', 'on') %}
        mdi:valve-open
        {% else %}
        mdi:valve-closed
        {% endif %}
