- platform: template
  sensors:
    li_thermostat_valve:
      friendly_name: 'Термостат гостиная'
      value_template: >-
        {{ states('sensor.li_thermostat_position') | default(0) | int > 0 }}
      device_class: lock
      icon_template: >-
        {% if is_state('binary_sensor.li_thermostat_valve', 'on') %}
        mdi:valve-open
        {% else %}
        mdi:valve-closed
        {% endif %}
