- platform: template
  sensors:
    last_google_backup_train:
      friendly_name: 'Последний удачный бэкап'
      value_template: >
        {% if states.sensor.snapshot_backup %}
          {{ (as_timestamp(states.sensor.snapshot_backup.attributes.last_snapshot)) | timestamp_custom("%d.%m.%Y %H:%M") }}
        {% else %}
          Not initialized yet
        {% endif %}
      icon_template: mdi:calendar-check-outline

    snapshots_in_google_drive_train:
      friendly_name: 'Снапшотов на Google Drive'
      value_template: >
        {% if states.sensor.snapshot_backup %}
          {{ states.sensor.snapshot_backup.attributes.snapshots_in_google_drive }}
        {% else %}
          Not initialized yet
        {% endif %}
      icon_template: mdi:folder-google-drive

    snapshots_in_hassio_train:
      friendly_name: 'Снапшотов в Наssio'
      value_template: >
        {% if states.sensor.snapshot_backup %}
          {{ states.sensor.snapshot_backup.attributes.snapshots_in_hassio }}
        {% else %}
          Not initialized yet
        {% endif %}
      icon_template: mdi:home-assistant
