- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'time_date'

- platform: systemmonitor
  resources:
  - type: processor_use
  - type: disk_use_percent
    arg: /
  - type: memory_use_percent
  - type: last_boot
  - type: disk_free
    arg: /

- platform: sql
  queries:
    - name: 'DB size'
      query: 'SELECT (page_count * page_size)/1024/1024 as size FROM pragma_page_count(), pragma_page_size();'
      column: 'size'
      unit_of_measurement: 'MBi'

# Время с последней перезагрузки системы
- platform: template
  sensors:
    last_boot_human:
      friendly_name: "Последняя перезагрузка системы"
      value_template: >
        {% set uptime = as_timestamp (now()) - as_timestamp(states.sensor.last_boot.state) | int %}
        {% set minutes = (( uptime % 3600) / 60) | int %}
        {% set hours = ((uptime % 86400) / 3600) | int %}
        {% set days = (uptime / 86400) | int %}

        {% if uptime < 1 %}
          Меньше минуты
        {% else %}
          {% if days > 0 %}
            {{ days }} д.
          {% endif %}
          {% if hours > 0 %}
            {% if days > 0 %}
              {{ ' ' }}
            {% endif %}
            {{ hours }} ч.
          {% endif %}
          {% if minutes > 0 %}
            {% if days > 0 or hours > 0 %}
              {{ ' ' }}
            {% endif %}
              {{ minutes }} мин.
          {% endif %}
        {% endif %}
      icon_template: mdi:clock

- platform: template
  sensors:
   online_human:
    friendly_name: "Home Assistant в онлайне"
    value_template: >
      {% set uptime = as_timestamp(now()) | int - as_timestamp(states.sensor.online.state) | int %}
      {% set minutes = ( uptime / (60) % 60) | int %}
      {% set hours = (uptime / (60 * 60) % 24) | int %}
      {% set days = (uptime / (60 * 60 * 24)) | int %}

      {% if uptime < 1 %}
        Меньше минуты
      {% else %}
        {% if days > 0 %}
          {{ days }} д.
        {% endif %}
        {% if hours > 0 %}
          {% if days > 0 %}
            {{ ' ' }}
          {% endif %}
          {{ hours }} ч.
        {% endif %}
        {% if minutes > 0 %}
          {% if days > 0 or hours > 0 %}
            {{ ' ' }}
          {% endif %}
            {{ minutes }} мин.
        {% endif %}
      {% endif %}
    icon_template: mdi:clock
