- platform: template
  sensors:
    vacuum_start_time_weekdays:
      friendly_name: 'Время начала уборки (будни)'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.vacuum_start_hour_weekdays") | int, states("input_number.vacuum_start_minutes_weekdays") | int) }}'
    vacuum_start_time_weekend:
      friendly_name: 'Время начала уборки (выходные)'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.vacuum_start_hour_weekend") | int, states("input_number.vacuum_start_minutes_weekend") | int) }}'
    vacuum_status:
      friendly_name: "Пылесос - Статус"
      value_template: "Cостояние: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}"
    vacuum_weekdays:
      friendly_name: "Пылесос - Будни"
      value_template: "Будний день:"
    vacuum_weekend:
      friendly_name: "Пылесос - Выходные"
      value_template: "Выходные:"
    vacuum_battery:
      friendly_name: "Пылесос - Battery"
      value_template: "Аккумулятор: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_level }}"
      device_class: battery
      unit_of_measurement: '%'
    vacuum_accessories:
      friendly_name: "Пылесос - Aксессуары"
      value_template: "Подробности статуса"
    vacuum_operation:
      friendly_name: "Пылесос - Операция"
      value_template: "Операция"
    vacuum_main_brush:
      friendly_name: "Пылесос - Основная щётка"
      value_template: "Основная щётка: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.main_brush_left }} h"
    vacuum_side_brush:
      friendly_name: "Пылесос - Боковая щётка"
      value_template: "Боковая щётка: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.side_brush_left }} h"
    vacuum_filter:
      friendly_name: "Пылесос - Фильтр"
      value_template: "Фильтр: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.filter_left }} h"
    vacuum_sensor:
      friendly_name: "Пылесос - Датчики"
      value_template: "Датчики: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.sensor_dirty_left }} h"