- platform: template
  switches:
    be_boiler_channel:
      friendly_name: 'Котёл канал спальни'
      value_template: >-
        {{ is_state('switch.kn_boilerone_switch_l1', 'on') }}
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.kn_boilerone_switch_l1
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.kn_boilerone_switch_l1
      icon_template: >-
        {% if is_state("switch.kn_boilerone_switch_l1", "on") %}
        mdi:radiator
        {% else %}
        mdi:radiator-disabled
        {% endif %}

    ch_boiler_channel:
      friendly_name: 'Котёл канал детской'
      value_template: >-
        {{ is_state('switch.kn_boilerone_switch_l2', 'on') }}
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.kn_boilerone_switch_l2
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.kn_boilerone_switch_l2
      icon_template: >-
        {% if is_state("switch.kn_boilerone_switch_l2", "on") %}
        mdi:radiator
        {% else %}
        mdi:radiator-disabled
        {% endif %}

    li_boiler_channel:
      friendly_name: 'Котёл канал гостиной'
      value_template: >-
        {{ is_state('switch.kn_boilertwo_switch_l1', 'on') }}
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.kn_boilertwo_switch_l1
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.kn_boilertwo_switch_l1
      icon_template: >-
        {% if is_state("switch.kn_boilertwo_switch_l1", "on") %}
        mdi:radiator
        {% else %}
        mdi:radiator-disabled
        {% endif %}
