- platform: template
  switches:
    co_mirror_socket:
      friendly_name: 'Розетка зеркала'
      value_template: >-
        {{ is_state('switch.co_mirror_switch_l1', 'on') }}
      turn_on:
        - service: switch.turn_on
          entity_id: switch.co_mirror_switch_l1
      turn_off:
        - service: switch.turn_off
          entity_id: switch.co_mirror_switch_l1
      icon_template: >-
        {% if is_state('switch.co_mirror_switch_l1', 'on') %}
        mdi:power-plug
        {% else %}
        mdi:power-plug-off
        {% endif %}
