- platform: template
  switches:
    be_boiler_channel:
      friendly_name: 'Обогрев спальни'
      value_template: >-
        {{ is_state('switch.kn_boilerone_switch_l1', 'on') }}
      turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.kn_boilerone_switch_l1
        - service: mqtt.publish
          data:
            topic: 'zigbee2mqtt/BE_Thermostat/set'
            payload: '{"system_mode": "boost"}'
      turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.kn_boilerone_switch_l1
        - service: mqtt.publish
          data:
            topic: 'zigbee2mqtt/BE_Thermostat/set'
            payload: '{"system_mode": "off"}'
      icon_template: >-
        {% if is_state('switch.kn_boilerone_switch_l1', 'on') %}
        mdi:radiator
        {% else %}
        mdi:radiator-disabled
        {% endif %}

    ch_boiler_channel:
      friendly_name: 'Обогрев детской'
      value_template: >-
        {{ is_state('switch.kn_boilerone_switch_l2', 'on') }}
      turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.kn_boilerone_switch_l2
        - service: mqtt.publish
          data:
            topic: 'zigbee2mqtt/CH_Thermostat/set'
            payload: '{"system_mode": "boost"}'
      turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.kn_boilerone_switch_l2
        - service: mqtt.publish
          data:
            topic: 'zigbee2mqtt/CH_Thermostat/set'
            payload: '{"system_mode": "off"}'
      icon_template: >-
        {% if is_state('switch.kn_boilerone_switch_l2', 'on') %}
        mdi:radiator
        {% else %}
        mdi:radiator-disabled
        {% endif %}

    li_boiler_channel:
      friendly_name: 'Обогрев гостиной'
      value_template: >-
        {{ is_state('switch.kn_boilertwo_switch_l1', 'on') }}
      turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.kn_boilertwo_switch_l1
        - service: mqtt.publish
          data:
            topic: 'zigbee2mqtt/LI_Thermostat/set'
            payload: '{"system_mode": "boost"}'
      turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.kn_boilertwo_switch_l1
        - service: mqtt.publish
          data:
            topic: 'zigbee2mqtt/LI_Thermostat/set'
            payload: '{"system_mode": "off"}'
      icon_template: >-
        {% if is_state('switch.kn_boilertwo_switch_l1', 'on') %}
        mdi:radiator
        {% else %}
        mdi:radiator-disabled
        {% endif %}
