homeassistant:
  customize:
    light.slshubli_led:
      friendly_name: 'Ночник в гостиной'


timer:
  li_sls_reboot:
    name: Недоступность шлюза в гостиной
    duration: 300


mqtt:
  switch:
    - name: li_sls_join
      state_topic: 'SLSHubLI/bridge/config/permit_join'
      command_topic: 'SLSHubLI/bridge/config/permit_join'
      payload_on: 'true'
      payload_off: 'false'

  sensor:
    - name: li_sls_version
      state_topic: 'SLSHubLI/bridge/config'
      value_template: '{{ value_json.Version }}'

  binary_sensor:
    - name: li_sls_state
      state_topic: 'SLSHubLI/bridge/state'
      payload_on: 'online'
      payload_off: 'offline'


automation:
  - id: 'Шлюз в гостиной оффлайн, запустить таймер недоступности'
    alias: li_offline_sls
    trigger:
      - platform: state
        entity_id: binary_sensor.li_sls_state
        to: 'off'
    action:
      - service: timer.start
        entity_id: timer.li_sls_reboot

  - id: 'Шлюз в гостиной онлайн, отменить таймер недоступности'
    alias: li_online_sls
    trigger:
      - platform: state
        entity_id: binary_sensor.li_sls_state
        to: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.li_sls_reboot

  - id: 'Уведомить о недоступности SLS шлюза в гостиной и запустить перезагрузку'
    alias: li_reboot_sls
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.li_sls_reboot
    action:
      - service: script.reboot_sls
        data:
          name: 'SLSHubLI'
