homeassistant:
  customize:
    light.slshubha_led:
      friendly_name: 'Ночник в прихожей'


timer:
  ha_sls_reboot:
    name: Недоступность шлюза в прихожей
    duration: 300


mqtt:
  switch:
    - name: ha_sls_join
      state_topic: 'SLSHubHA/bridge/config/permit_join'
      command_topic: 'SLSHubHA/bridge/config/permit_join'
      payload_on: 'true'
      payload_off: 'false'

  sensor:
    - name: ha_sls_version
      state_topic: 'SLSHubHA/bridge/config'
      value_template: '{{ value_json.Version }}'

  binary_sensor:
    - name: ha_sls_state
      state_topic: 'SLSHubHA/bridge/state'
      payload_on: 'online'
      payload_off: 'offline'


automation:
  - id: 'Шлюз в прихожей оффлайн, запустить таймер недоступности'
    alias: ha_offline_sls
    trigger:
      - platform: state
        entity_id: binary_sensor.ha_sls_state
        to: 'off'
    action:
      - service: timer.start
        entity_id: timer.ha_sls_reboot

  - id: 'Шлюз в прихожей онлайн, отменить таймер недоступности'
    alias: ha_online_sls
    trigger:
      - platform: state
        entity_id: binary_sensor.ha_sls_state
        to: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.ha_sls_reboot

  - id: 'Уведомить о недоступности SLS шлюза в прихожей и запустить перезагрузку'
    alias: ha_reboot_sls
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.ha_sls_reboot
    action:
      - service: script.reboot_sls
        data:
          name: 'SLSHubHA'
