homeassistant:
  customize:
    light.slshubbe_led:
      friendly_name: 'Ночник в спальне'


timer:
  be_sls_reboot:
    name: Недоступность шлюза в спальне
    duration: 300


mqtt:
  switch:
    - name: be_sls_join
      state_topic: 'SLSHubBE/bridge/config/permit_join'
      command_topic: 'SLSHubBE/bridge/config/permit_join'
      payload_on: 'true'
      payload_off: 'false'

  sensor:
    - name: be_sls_version
      state_topic: 'SLSHubBE/bridge/config'
      value_template: '{{ value_json.Version }}'

  binary_sensor:
    - name: be_sls_state
      state_topic: 'SLSHubBE/bridge/state'
      payload_on: 'online'
      payload_off: 'offline'


automation:
  - id: 'Шлюз в спальне оффлайн, запустить таймер недоступности'
    alias: be_offline_sls
    trigger:
      - platform: state
        entity_id: binary_sensor.be_sls_state
        to: 'off'
    action:
      - service: timer.start
        entity_id: timer.be_sls_reboot

  - id: 'Шлюз в спальне онлайн, отменить таймер недоступности'
    alias: be_online_sls
    trigger:
      - platform: state
        entity_id: binary_sensor.be_sls_state
        to: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.be_sls_reboot

  - id: 'Уведомить о недоступности SLS шлюза в спальне и запустить перезагрузку'
    alias: be_reboot_sls
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.be_sls_reboot
    action:
      - service: script.reboot_sls
        data:
          name: 'SLSHubBE'
