homeassistant:
  customize:
    light.slshubkn_led:
      friendly_name: 'Ночник на кухне'


timer:
  kn_sls_reboot:
    name: Недоступность шлюза на кухне
    duration: 300


mqtt:
  switch:
    - name: kn_sls_join
      state_topic: 'SLSHubKN/bridge/config/permit_join'
      command_topic: 'SLSHubKN/bridge/config/permit_join'
      payload_on: 'true'
      payload_off: 'false'

  sensor:
    - name: kn_sls_version
      state_topic: 'SLSHubKN/bridge/config'
      value_template: '{{ value_json.Version }}'

  binary_sensor:
    - name: kn_sls_state
      state_topic: 'SLSHubKN/bridge/state'
      payload_on: 'online'
      payload_off: 'offline'


automation:
  - id: 'Шлюз на кухне оффлайн, запустить таймер недоступности'
    alias: kn_offline_sls
    trigger:
      - platform: state
        entity_id: binary_sensor.kn_sls_state
        to: 'off'
    action:
      - service: timer.start
        entity_id: timer.kn_sls_reboot

  - id: 'Шлюз на кухне онлайн, отменить таймер недоступности'
    alias: kn_online_sls
    trigger:
      - platform: state
        entity_id: binary_sensor.kn_sls_state
        to: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.kn_sls_reboot

  - id: 'Уведомить о недоступности SLS шлюза на кухне и запустить перезагрузку'
    alias: kn_reboot_sls
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.kn_sls_reboot
    action:
      - service: script.reboot_sls
        data:
          name: 'SLSHubKN'
