homeassistant:
  customize:
    light.slshubkn_led:
      friendly_name: 'Ночник на кухне'

mqtt:
  switch:
    - name: kn_sls_join
      state_topic: 'SLSHubKN/bridge/config/permit_join'
      command_topic: 'SLSHubKN/bridge/config/permit_join'
      payload_on: 'true'
      payload_off: 'false'

  sensor:
    - name: kn_sls_version
      state_topic: 'SLSHubKN/bridge/config'
      value_template: '{{ value_json.Version }}'

  binary_sensor:
    - name: kn_sls_state
      state_topic: 'SLSHubKN/bridge/state'
      payload_on: 'online'
      payload_off: 'offline'
