- platform: template
  switches:
    be_boiler_channel:
      friendly_name: 'Обогрев спальни'
      value_template: >-
        {{ is_state('switch.kn_boilerone_switch_l1', 'on') }}
      turn_on:
        - service: switch.turn_on
          entity_id: switch.kn_boilerone_switch_l1
        - service: switch.turn_on
          entity_id: switch.be_breezer_ptc
        - service: mqtt.publish
          data:
            topic: 'SLSHubBE/BE_Thermostat/set'
            payload: '{"force": "normal"}'
        - service: mqtt.publish
          data:
            topic: 'SLSHubBE/BE_Thermostat/set'
            payload: '{"current_heating_setpoint": "25"}'
      turn_off:
        - service: switch.turn_off
          entity_id: switch.kn_boilerone_switch_l1
        - service: switch.turn_off
          entity_id: switch.be_breezer_ptc
        - service: mqtt.publish
          data:
            topic: 'SLSHubBE/BE_Thermostat/set'
            payload: '{"force": "close"}'
      icon_template: >-
        {% if is_state('switch.kn_boilerone_switch_l1', 'on') %}
        mdi:radiator
        {% else %}
        mdi:radiator-disabled
        {% endif %}
