- platform: template
  switches:
    li_boiler_channel:
      friendly_name: 'Обогрев гостиной'
      value_template: >-
        {{ is_state('switch.kn_boilertwo_switch_l1', 'on') }}
      turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.kn_boilertwo_switch_l1
        - service: mqtt.publish
          data:
            topic: 'SLSHubKN/LI_Thermostat/set'
            payload: '{"force": "normal"}'
        - service: mqtt.publish
          data:
            topic: 'SLSHubKN/LI_Thermostat/set'
            payload: '{"current_heating_setpoint": "25"}'
      turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.kn_boilertwo_switch_l1
        - service: mqtt.publish
          data:
            topic: 'SLSHubKN/LI_Thermostat/set'
            payload: '{"force": "close"}'
      icon_template: >-
        {% if is_state('switch.kn_boilertwo_switch_l1', 'on') %}
        mdi:radiator
        {% else %}
        mdi:radiator-disabled
        {% endif %}
