recorder:
  auto_purge: true
  purge_keep_days: 14
  commit_interval: 3600

  include:
    domains:
      - sensor
      - climate
      - media_player

automation:
  - id: 'Сжатие базы'
    alias: 00_purge_everyday
    trigger:
      - platform: time
        at: '01:00:00'
    action:
      - service: recorder.purge
        data:
          keep_days: 14
          repack: true
