timer:
  kn_tv:
    name: Телевизор на кухне
    duration: '00:14:00'
  kn_tv_back:
    name: Телевизор на кухне (включение)
    duration: '00:01:00'

automation:
  - id: 'Запустить таймер при включении телевизора на кухне'
    alias: kn_start_timer_on_tv_switched_on
    trigger:
      - platform: state
        entity_id: media_player.samsung_5
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.kn_motion_occupancy
        state: 'off'
      - condition: state
        entity_id: binary_sensor.kn_motiontable_occupancy
        state: 'off'
      - condition: state
        entity_id: binary_sensor.kn_motionpicture_occupancy
        state: 'off'
    action:
      - service: timer.start
        entity_id: timer.kn_tv

  - id: 'Отменять таймер при включённом телевизорe и появлении движения на датчиках кухни'
    alias: kn_stop_timer_on_tv_switched_on_and_motion_detected
    trigger:
      - platform: state
        entity_id: binary_sensor.kn_motion_occupancy
        to: 'on'
      - platform: state
        entity_id: binary_sensor.kn_motiontable_occupancy
        to: 'on'
      - platform: state
        entity_id: binary_sensor.kn_motionpicture_occupancy
        to: 'on'
    condition:
      - or:
          - condition: state
            entity_id: media_player.samsung_5
            state: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.kn_tv

  - id: 'Запускать таймер при включённом телевизоре и отсутствии движения на датчиках кухни'
    alias: kn_start_timer_on_tv_switched_on_and_no_motion_detected
    trigger:
      - platform: state
        entity_id: binary_sensor.kn_motion_occupancy
        to: 'off'
      - platform: state
        entity_id: binary_sensor.kn_motiontable_occupancy
        to: 'off'
      - platform: state
        entity_id: binary_sensor.kn_motionpicture_occupancy
        to: 'off'
    condition:
      - condition: state
        entity_id: binary_sensor.kn_motion_occupancy
        state: 'off'
      - condition: state
        entity_id: binary_sensor.kn_motiontable_occupancy
        state: 'off'
      - condition: state
        entity_id: binary_sensor.kn_motionpicture_occupancy
        state: 'off'
      - or:
          - condition: state
            entity_id: media_player.samsung_5
            state: 'on'
    action:
      - service: timer.start
        entity_id: timer.kn_tv

  - id: 'Остановить таймер при выключении телевизора на кухне'
    alias: kn_cancel_timer_on_tv_switched_off
    trigger:
      - platform: state
        entity_id: media_player.samsung_5
        to: 'off'
    action:
      - service: timer.cancel
        entity_id: timer.kn_tv

  - id: 'Выключить телевизор на кухне по таймеру'
    alias: kn_disable_tv_on_timer_finished
    initial_state: true
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.kn_tv
    action:
      - service: media_player.turn_off
        entity_id: media_player.samsung_5
      - service: timer.start
        entity_id: timer.kn_tv_back

  - id: 'Включить телевизор при появлении движения на датчиках кухни если таймер после отключения работает'
    alias: kn_enable_tv_on_motion_detected_during_back_timer
    trigger:
      - platform: state
        entity_id: binary_sensor.kn_motion_occupancy
        to: 'on'
      - platform: state
        entity_id: binary_sensor.kn_motiontable_occupancy
        to: 'on'
      - platform: state
        entity_id: binary_sensor.kn_motionpicture_occupancy
        to: 'on'
    condition:
      - condition: state
        entity_id: timer.kn_tv_back
        state: 'active'
    action:
      - service: media_player.turn_on
        entity_id: media_player.samsung_5
