homeassistant:
  customize:
    light.be_bedlight_alexey_light:
      friendly_name: 'Прикроватная лампа слева'

automation:
  - id: 'Переключение прикроватной лампы слева'
    alias: be_bedlight_alexey_toggle
    trigger:
      - platform: state
        entity_id: sensor.be_controlone_action
        to: left
      - platform: state
        entity_id: sensor.be_controltwo_action
        to: left
      - platform: state
        entity_id: sensor.be_controlone_action
        to: both
      - platform: state
        entity_id: sensor.be_controltwo_action
        to: both
    action:
      - service: light.toggle
        target:
          entity_id: light.be_bedlight_alexey_light

  - id: 'Включение прикроватной лампы слева, белый свет'
    alias: be_bedlight_alexey_on_white
    trigger:
      - platform: state
        entity_id: sensor.be_controlone_action
        to: left_double
      - platform: state
        entity_id: sensor.be_controltwo_action
        to: left_double
    action:
      - service: light.turn_on
        target:
          entity_id: light.be_bedlight_alexey_light
        data:
          brightness_pct: 100
          color_temp: 500

  - id: 'Включение прикроватной лампы слева, цветной свет'
    alias: be_bedlight_alexey_on_color
    trigger:
      - platform: state
        entity_id: sensor.be_controlone_action
        to: left_hold
      - platform: state
        entity_id: sensor.be_controltwo_action
        to: left_hold
      - platform: state
        entity_id: sensor.be_controlone_action
        to: both_hold
      - platform: state
        entity_id: sensor.be_controltwo_action
        to: both_hold
    action:
      - service: light.turn_on
        target:
          entity_id: light.be_bedlight_alexey_light
        data:
          brightness_pct: 100
          rgb_color: [255, 0, 0]
