homeassistant:
  customize:
    light.be_bedlight_julia_light:
      friendly_name: 'Прикроватная лампа справа'


automation:
  - id: 'Переключение прикроватной лампы справа'
    alias: be_bedlight_julia_toggle
    trigger:
      - platform: state
        entity_id: sensor.be_controlone_action
        to: right
      - platform: state
        entity_id: sensor.be_controltwo_action
        to: right
      - platform: state
        entity_id: sensor.be_controlone_action
        to: both
      - platform: state
        entity_id: sensor.be_controltwo_action
        to: both
    action:
      - service: light.toggle
        target:
          entity_id: light.be_bedlight_julia_light

  - id: 'Включение прикроватной лампы справа, белый свет'
    alias: be_bedlight_julia_on_white
    trigger:
      - platform: state
        entity_id: sensor.be_controlone_action
        to: right_double
      - platform: state
        entity_id: sensor.be_controltwo_action
        to: right_double
    action:
      - service: light.turn_on
        target:
          entity_id: light.be_bedlight_julia_light
        data:
          brightness_pct: 100
          color_temp: 500

  - id: 'Включение прикроватной лампы справа, цветной свет'
    alias: be_bedlight_julia_on_color
    trigger:
      - platform: state
        entity_id: sensor.be_controlone_action
        to: right_hold
      - platform: state
        entity_id: sensor.be_controltwo_action
        to: right_hold
      - platform: state
        entity_id: sensor.be_controlone_action
        to: both_hold
      - platform: state
        entity_id: sensor.be_controltwo_action
        to: both_hold
    action:
      - service: light.turn_on
        target:
          entity_id: light.be_bedlight_julia_light
        data:
          brightness_pct: 100
          rgb_color: [255, 0, 0]
