light:
  - platform: template
    lights:
      be_light:
        friendly_name: 'Свет в спальне'
        value_template: >-
          {{ is_state('switch.be_light_switch_right', 'on') }}
        turn_on:
          - service: switch.turn_on
            entity_id: switch.be_light_switch_right
        turn_off:
          - service: switch.turn_off
            entity_id: switch.be_light_switch_right


automation:
  - id: 'Переключение света в спальне с пультов'
    alias: be_light_left_remote_toggle
    trigger:
      - platform: state
        entity_id: sensor.be_controlone_action
        to: both_double
      - platform: state
        entity_id: sensor.be_controltwo_action
        to: both_double
    action:
      - service: light.toggle
        target:
          entity_id: light.be_light
