light:
  - platform: template
    lights:
      ch_upper_light:
        friendly_name: 'Гирлянда на шторах в детской'
        value_template: >-
          {{ is_state('switch.ch_upperlight_switch', 'on') }}
        turn_on:
          - service: switch.turn_on
            entity_id: switch.ch_upperlight_switch
        turn_off:
          - service: switch.turn_off
            entity_id: switch.ch_upperlight_switch


automation:
  - id: 'Включить гирлянду в детской за полчаса до заката'
    alias: ch_enable_upper_light_on_30_min_before_sunset
    trigger:
      - platform: sun
        event: sunset
        offset: '-00:30:00'
    action:
      - service: light.turn_on
        entity_id: light.ch_upper_light

  - id: 'Выключить гирлянду в детской в 23:00'
    alias: ch_disable_upper_light_on_time
    trigger:
      - platform: time
        at: '23:00:00'
    action:
      - service: light.turn_off
        entity_id: light.ch_upper_light
