timer:
  co_light:
    name: Свет в коридоре
    duration: 180
  co_light_back:
    name: Свет в коридоре (включение)
    duration: '00:01:00'

light:
  - platform: template
    lights:
      co_light:
        friendly_name: 'Основной свет в коридоре'
        value_template: >-
          {{ is_state('switch.co_light_switch', 'on') }}
        turn_on:
          - service: switch.turn_on
            entity_id: switch.co_light_switch
        turn_off:
          - service: switch.turn_off
            entity_id: switch.co_light_switch

automation:
  - id: 'Запустить таймер при включении света в коридоре'
    alias: co_start_timer_on_light_switched_on
    trigger:
      - platform: state
        entity_id: light.co_light
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.co_motionbathroom_occupancy
        state: 'off'
      - condition: state
        entity_id: binary_sensor.co_motionkitchen_occupancy
        state: 'off'
      - condition: state
        entity_id: binary_sensor.co_motionmirror_occupancy
        state: 'off'
    action:
      - service: timer.start
        entity_id: timer.co_light
      - service: automation.turn_on
        entity_id: automation.co_start_timer_on_light_switched_on_and_no_motion_detected

  - id: 'Отменять таймер при включённом свете и появлении движения на датчиках коридора'
    alias: co_stop_timer_on_light_switched_on_and_motion_detected
    trigger:
      - platform: state
        entity_id: binary_sensor.co_motionbathroom_occupancy
        to: 'on'
      - platform: state
        entity_id: binary_sensor.co_motionkitchen_occupancy
        to: 'on'
      - platform: state
        entity_id: binary_sensor.co_motionmirror_occupancy
        to: 'on'
    condition:
      - condition: state
        entity_id: light.co_light
        state: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.co_light

  - id: 'Запускать таймер при включённом свете и отсутствии движения на всех датчиках коридора'
    alias: co_start_timer_on_light_switched_on_and_no_motion_detected
    trigger:
      - platform: state
        entity_id: binary_sensor.co_motionbathroom_occupancy
        to: 'off'
      - platform: state
        entity_id: binary_sensor.co_motionkitchen_occupancy
        to: 'off'
      - platform: state
        entity_id: binary_sensor.co_motionmirror_occupancy
        to: 'off'
    condition:
      - condition: state
        entity_id: light.co_light
        state: 'on'
      - condition: state
        entity_id: binary_sensor.co_motionbathroom_occupancy
        state: 'off'
      - condition: state
        entity_id: binary_sensor.co_motionkitchen_occupancy
        state: 'off'
      - condition: state
        entity_id: binary_sensor.co_motionmirror_occupancy
        state: 'off'
    action:
      - service: timer.start
        entity_id: timer.co_light

  - id: 'Остановить таймер при выключении света в коридоре'
    alias: co_cancel_timer_on_light_switched_off
    trigger:
      - platform: state
        entity_id: light.co_light
        to: 'off'
    action:
      - service: timer.cancel
        entity_id: timer.co_light

  - id: 'Выключить свет в коридоре по таймеру'
    alias: co_disable_light_on_timer_finished
    initial_state: true
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.co_light
    action:
      - service: light.turn_off
        entity_id: light.co_light
      - service: timer.start
        entity_id: timer.co_light_back

  - id: 'Переключить свет в коридоре с ремоута возле спальни'
    alias: co_enable_light_using_remote
    initial_state: false
    trigger:
      - platform: state
        entity_id: sensor.co_lightremote_action
        to: 'single'
    action:
      - service: light.toggle
        entity_id: light.co_light

  - id: 'Убрать таймер для света в коридоре с ремоута возле спальни'
    alias: co_disable_timer_using_remote
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.co_lightremote_action
        to: 'double'
    action:
      - service: timer.cancel
        entity_id: timer.co_light
      - service: automation.turn_off
        entity_id: automation.co_start_timer_on_light_switched_on_and_no_motion_detected

  - id: 'Выключить весь свет в коридоре'
    alias: co_disable_all_light
    trigger:
      - platform: state
        entity_id: sensor.co_lightremote_action
        to: 'hold'
      - platform: state
        entity_id: sensor.co_light_action
        to: 'hold'
      - platform: state
        entity_id: sensor.ha_light_action
        to: 'hold'
    action:
      - service: light.turn_off
        entity_id: light.co_light
      - service: light.turn_off
        entity_id: light.co_mirror_light
      - service: light.turn_off
        entity_id: light.ha_light

  - id: 'Включить свет в коридоре при появлении движения на датчиках коридора если таймер после отключения работает'
    alias: co_enable_light_on_motion_detected_during_back_timer
    trigger:
      - platform: state
        entity_id: binary_sensor.co_motionbathroom_occupancy
        to: 'on'
      - platform: state
        entity_id: binary_sensor.co_motionkitchen_occupancy
        to: 'on'
      - platform: state
        entity_id: binary_sensor.co_motionmirror_occupancy
        to: 'on'
    condition:
      - condition: state
        entity_id: timer.co_light_back
        state: 'active'
    action:
      - service: light.turn_on
        entity_id: light.co_light

  - id: 'Выключить таймер восстановления при включении света в коридоре'
    alias: co_cancel_back_timer_on_light_switched_on
    trigger:
      - platform: state
        entity_id: light.co_light
        to: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.co_light_back
