timer:
  co_mirror_light:
    name: Подсветка зеркала
    duration: 180
  co_mirror_light_back:
    name: Подсветка зеркала (включение)
    duration: '00:01:00'

light:
  - platform: template
    lights:
      co_mirror_light:
        friendly_name: 'Подсветка зеркала'
        value_template: >-
          {{ is_state('switch.co_mirror_switch_l2', 'on') }}
        turn_on:
          - service: switch.turn_on
            entity_id: switch.co_mirror_switch_l2
        turn_off:
          - service: switch.turn_off
            entity_id: switch.co_mirror_switch_l2

automation:
  - id: 'Запустить таймер при включении подсветки зеркала в коридоре'
    alias: co_start_timer_on_mirror_light_switched_on
    trigger:
      - platform: state
        entity_id: light.co_mirror_light
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.co_motionmirror_occupancy
        state: 'off'
    action:
      - service: timer.start
        entity_id: timer.co_mirror_light

  - id: 'Отменить таймер при появлении движения на датчике зеркала и включённой подсветке зеркала'
    alias: co_stop_timer_on_occupancy_start_and_mirror_light_on
    trigger:
      - platform: state
        entity_id: binary_sensor.co_motionmirror_occupancy
        to: 'on'
    condition:
      - condition: state
        entity_id: light.co_mirror_light
        state: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.co_mirror_light

  - id: 'Запустить таймер при отсутствии движения на датчике зеркала и включённой подсветке зеркала'
    alias: co_start_timer_on_occupancy_finish_and_mirror_light_on
    trigger:
      - platform: state
        entity_id: binary_sensor.co_motionmirror_occupancy
        to: 'off'
    condition:
      - condition: state
        entity_id: light.co_mirror_light
        state: 'on'
    action:
      - service: timer.start
        entity_id: timer.co_mirror_light

  - id: 'Остановить таймер при выключении подсветки зеркала'
    alias: co_cancel_timer_on_mirror_light_switched_off
    trigger:
      - platform: state
        entity_id: light.co_mirror_light
        to: 'off'
    action:
      - service: timer.cancel
        entity_id: timer.co_mirror_light

  - id: 'Выключить подсветку зеркала в коридоре по таймеру'
    alias: co_disable_mirror_light_on_timer_finished
    initial_state: true
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.co_mirror_light
    action:
      - service: light.turn_off
        entity_id: light.co_mirror_light
      - service: timer.start
        entity_id: timer.co_mirror_light_back

  - id: 'Включить подсветку зеркала в коридоре при появлении движения на датчике если таймер после отключения работает'
    alias: co_enable_mirror_light_on_motion_detected_during_back_timer
    trigger:
      - platform: state
        entity_id: binary_sensor.co_motionmirror_occupancy
        to: 'on'
    condition:
      - condition: state
        entity_id: timer.co_mirror_light_back
        state: 'active'
    action:
      - service: light.turn_on
        entity_id: light.co_mirror_light

  - id: 'Выключить таймер восстановления при включении света в коридоре'
    alias: co_cancel_back_timer_on_mirror_light_switched_on
    trigger:
      - platform: state
        entity_id: light.co_mirror_light
        to: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.co_mirror_light_back
