timer:
  kn_light:
    name: Свет на кухне
    duration: '00:08:00'
  kn_light_back:
    name: Подсветка на кухне (включение)
    duration: '00:01:00'


light:
  - platform: template
    lights:
      kn_light:
        friendly_name: 'Свет на кухне'
        value_template: >-
          {{ is_state('switch.kn_light_switch_left', 'on') }}
        turn_on:
          - service: switch.turn_on
            entity_id: switch.kn_light_switch_left
        turn_off:
          - service: switch.turn_off
            entity_id: switch.kn_light_switch_left


automation:
  - id: 'Запустить таймер при включении света на кухне'
    alias: kn_start_timer_on_light_switched_on
    trigger:
      - platform: state
        entity_id: light.kn_light
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.kn_motion_occupancy
        state: 'off'
      - condition: state
        entity_id: binary_sensor.kn_motiontable_occupancy
        state: 'off'
      - condition: state
        entity_id: binary_sensor.kn_motionpicture_occupancy
        state: 'off'
    action:
      - service: timer.start
        entity_id: timer.kn_light

  - id: 'Отменять таймер при включённом свете и появлении движения на датчиках кухни'
    alias: kn_stop_timer_on_light_switched_on_and_motion_detected
    trigger:
      - platform: state
        entity_id: binary_sensor.kn_motion_occupancy
        to: 'on'
      - platform: state
        entity_id: binary_sensor.kn_motiontable_occupancy
        to: 'on'
      - platform: state
        entity_id: binary_sensor.kn_motionpicture_occupancy
        to: 'on'
    condition:
      - or:
          - condition: state
            entity_id: light.kn_light
            state: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.kn_light

  - id: 'Запускать таймер при включённом свете и отсутствии движения на датчиках кухни'
    alias: kn_start_timer_on_light_switched_on_and_no_motion_detected
    trigger:
      - platform: state
        entity_id: binary_sensor.kn_motion_occupancy
        to: 'off'
      - platform: state
        entity_id: binary_sensor.kn_motiontable_occupancy
        to: 'off'
      - platform: state
        entity_id: binary_sensor.kn_motionpicture_occupancy
        to: 'off'
    condition:
      - condition: state
        entity_id: binary_sensor.kn_motion_occupancy
        state: 'off'
      - condition: state
        entity_id: binary_sensor.kn_motiontable_occupancy
        state: 'off'
      - condition: state
        entity_id: binary_sensor.kn_motionpicture_occupancy
        state: 'off'
      - or:
          - condition: state
            entity_id: light.kn_light
            state: 'on'
    action:
      - service: timer.start
        entity_id: timer.kn_light

  - id: 'Остановить таймер при выключении света на кухне'
    alias: kn_cancel_timer_on_light_switched_off
    trigger:
      - platform: state
        entity_id: light.kn_light
        to: 'off'
    action:
      - service: timer.cancel
        entity_id: timer.kn_light

  - id: 'Выключить свет на кухне по таймеру'
    alias: kn_disable_light_on_timer_finished
    initial_state: true
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.kn_light
    action:
      - service: light.turn_off
        entity_id: light.kn_light
      - service: timer.start
        entity_id: timer.kn_light_back

  - id: 'Включить свет на кухне при появлении движения на датчиках кухни если таймер после отключения работает'
    alias: kn_enable_light_on_motion_detected_during_back_timer
    trigger:
      - platform: state
        entity_id: binary_sensor.kn_motion_occupancy
        to: 'on'
      - platform: state
        entity_id: binary_sensor.kn_motiontable_occupancy
        to: 'on'
      - platform: state
        entity_id: binary_sensor.kn_motionpicture_occupancy
        to: 'on'
    condition:
      - condition: state
        entity_id: timer.kn_light_back
        state: 'active'
    action:
      - service: light.turn_on
        entity_id: light.kn_light

  - id: 'Выключить таймер восстановления при включении света на кухне'
    alias: kn_cancel_back_timer_on_light_switched_on
    trigger:
      - platform: state
        entity_id: light.kn_light
        to: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.kn_light_back

