timer:
  kn_night_light:
    name: Ночник на кухне
    duration: 120

automation:
  - id: 'Запустить таймер при включении ночника на кухне'
    alias: kn_start_timer_on_night_light_switched_on
    trigger:
      - platform: state
        entity_id: light.slshubkn_led
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.kn_motion_occupancy
        state: 'off'
      - condition: state
        entity_id: binary_sensor.kn_motiontable_occupancy
        state: 'off'
      - condition: state
        entity_id: binary_sensor.kn_motionpicture_occupancy
        state: 'off'
    action:
      - service: timer.start
        entity_id: timer.kn_night_light

  - id: 'Включить ночник на кухне при движении после захода солнца'
    alias: kn_enable_nightlight_after_sunset
    trigger:
      - platform: state
        entity_id: binary_sensor.kn_motion_occupancy
        to: 'on'
      - platform: state
        entity_id: binary_sensor.kn_motiontable_occupancy
        to: 'on'
      - platform: state
        entity_id: binary_sensor.kn_motionpicture_occupancy
        to: 'on'
    condition:
      - condition: template
        value_template: "{{ state_attr('sun.sun', 'elevation') < 1 }}"
      - condition: numeric_state
        entity_id: sensor.kn_motion_illuminance_raw
        below: 5
      - condition: numeric_state
        entity_id: sensor.kn_motiontable_illuminance_raw
        below: 5
      - condition: numeric_state
        entity_id: sensor.kn_motionpicture_illuminance_raw
        below: 5
      - condition: state
        entity_id: light.kn_light
        state: 'off'
      - condition: state
        entity_id: light.kn_ambient_light
        state: 'off'

    action:
      - service: light.turn_on
        data:
          entity_id: light.slshubkn_led
          brightness_pct: 80
          rgb_color: [255,0,0]

  - id: 'Отменять таймер при появлении движения на датчиках кухни'
    alias: kn_stop_timer_on_night_light_switched_on_and_motion_detected
    trigger:
      - platform: state
        entity_id: binary_sensor.kn_motion_occupancy
        to: 'on'
      - platform: state
        entity_id: binary_sensor.kn_motiontable_occupancy
        to: 'on'
      - platform: state
        entity_id: binary_sensor.kn_motionpicture_occupancy
        to: 'on'
    condition:
      - condition: state
        entity_id: light.slshubkn_led
        state: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.kn_night_light

  - id: 'Запускать таймер при включённом ночнике и отсутствии движения на всех датчиках кухни'
    alias: kn_start_timer_on_night_light_switched_on_and_no_motion_detected
    trigger:
      - platform: state
        entity_id: binary_sensor.kn_motion_occupancy
        to: 'off'
      - platform: state
        entity_id: binary_sensor.kn_motiontable_occupancy
        to: 'off'
      - platform: state
        entity_id: binary_sensor.kn_motionpicture_occupancy
        to: 'off'
    condition:
      - condition: state
        entity_id: light.slshubkn_led
        state: 'on'
      - condition: state
        entity_id: binary_sensor.kn_motion_occupancy
        state: 'off'
      - condition: state
        entity_id: binary_sensor.kn_motiontable_occupancy
        state: 'off'
      - condition: state
        entity_id: binary_sensor.kn_motionpicture_occupancy
        state: 'off'
    action:
      - service: timer.start
        entity_id: timer.kn_night_light

  - id: 'Выключить ночник на кухне если включили основной свет или достаточно другого освещения'
    alias: kn_disable_night_light_if_main_light_switched_on
    trigger:
      - platform: numeric_state
        entity_id: sensor.kn_motion_illuminance_raw
        above: 5
      - platform: numeric_state
        entity_id: sensor.kn_motiontable_illuminance_raw
        above: 5
      - platform: numeric_state
        entity_id: sensor.kn_motionpicture_illuminance_raw
        above: 5
      - platform: state
        entity_id: light.kn_light
        to: 'on'
      - platform: state
        entity_id: light.kn_ambient_light
        to: 'on'
    action:
      - service: light.turn_off
        entity_id: light.slshubkn_led

  - id: 'Выключить ночник на кухне по таймеру'
    alias: kn_disable_night_light_on_timer_finished
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.kn_night_light
    action:
      - service: light.turn_off
        entity_id: light.slshubkn_led
