fan:
  - platform: template
    fans:
      ba_venting:
        friendly_name: "Вытяжка в ванной"
        value_template: "{{ states('switch.ba_venting_switch') }}"
        turn_on:
          - service: switch.turn_on
            target:
              entity_id: switch.ba_venting_switch
        turn_off:
          - service: switch.turn_off
            target:
              entity_id: switch.ba_venting_switch

template:
    - sensor:
      - name: ba_humidity_diff
        device_class: humidity
        unit_of_measurement: '%'
        state: "{{ states('sensor.ba_temperature_humidity')|int(60) - states('sensor.kn_temperature_humidity')|int(60) }}"

automation:
  - id: 'Включить вытяжку в ванной при высокой влажности и выключенном свете'
    alias: ba_enable_venting_on_high_humidity
    trigger:
      - platform: numeric_state
        entity_id: sensor.ba_humidity_diff
        above: 10
    condition:
      - condition: state
        entity_id: light.ba_light
        state: 'off'
    action:
      - service: fan.turn_on
        target:
          entity_id: fan.ba_venting

  - id: 'Выключить вытяжку в ванной при нормальной влажности'
    alias: ba_disable_venting_on_normal_humidity
    trigger:
      - platform: numeric_state
        entity_id: sensor.ba_humidity_diff
        below: 5
    action:
      - service: fan.turn_off
        target:
          entity_id: fan.ba_venting

  - id: 'Включить вытяжку в ванной при высокой влажности вместе с выключением света'
    alias: ba_enable_venting_on_high_humidity_with_light_off
    trigger:
      - platform: state
        entity_id: light.ba_light
        to: 'off'
    condition:
      - condition: numeric_state
        entity_id: sensor.ba_humidity_diff
        above: 10
    action:
      - service: fan.turn_on
        target:
          entity_id: fan.ba_venting

  - id: 'Включить вытяжку в ванной при очень высокой влажности'
    alias: ba_enable_venting_on_very_high_humidity
    trigger:
      - platform: numeric_state
        entity_id: sensor.ba_humidity_diff
        above: 20
    action:
      - service: fan.turn_on
        target:
          entity_id: fan.ba_venting

  - id: 'После выключения вытяжки через минуту проверить значение влажности'
    alias: ba_check_humidity_in_on_minute_after_venting_disable
    trigger:
      - platform: state
        entity_id: fan.ba_venting
        to: 'off'
        for: '00:01:00'
    condition:
      - condition: numeric_state
        entity_id: sensor.ba_humidity_diff
        above: 10
    action:
      - service: fan.turn_on
        target:
          entity_id: fan.ba_venting

  - id: 'Каждые полчаса проверять влажность и выключить вытяжку в ванной при нормальной влажности'
    alias: ba_check_humidity_every_thirty_minutes
    trigger:
      - platform: time_pattern
        minutes: /30
    condition:
      - condition: numeric_state
        entity_id: sensor.ba_humidity_diff
        below: 5
    action:
      - service: fan.turn_off
        target:
          entity_id: fan.ba_venting
