switch:
  - platform: template
    switches:
      be_breezer_ptc:
        friendly_name: Обогреватель бризера в спальне
        value_template: "{{ is_state_attr('fan.be_breezer_source', 'ptc', True) }}"
        turn_on:
          service: xiaomi_miio_airpurifier.fan_set_ptc_on
          data:
            entity_id: fan.be_breezer_source
        turn_off:
          service: xiaomi_miio_airpurifier.fan_set_ptc_off
          data:
            entity_id: fan.be_breezer_source
        icon_template: >-
          {% if is_state_attr('fan.be_breezer_source', 'ptc', true) %}
          mdi:radiator
          {% else %}
          mdi:radiator-disabled
          {% endif %}

sensor:
  - platform: template
    sensors:
      be_breezer_ntc_temperature:
        friendly_name: Температура обогревателя у бризера в спальне
        value_template: "{{ state_attr('fan.be_breezer_source', 'ntc_temperature') }}"
        icon_template: mdi:sun-thermometer
        unit_of_measurement: '°C'
      be_breezer_temperature:
        friendly_name: Температура по бризеру в спальне
        value_template: "{{ state_attr('fan.be_breezer_source', 'temperature') }}"
        icon_template: mdi:thermometer
        unit_of_measurement: '°C'

automation:
  - id: 'Включить обогрев по расписанию утром при низкой температуре на улице днём'
    alias: be_breezer_scheduled_enable_ptc_on_low_temperature_morning
    trigger:
      - platform: time_pattern
        hours: 09
        minutes: 00
      - platform: numeric_state
        entity_id: sensor.ha_outdoor_temperature
        below: 10
    condition:
      - condition: numeric_state
        entity_id: sensor.ha_outdoor_temperature
        below: 10
      - condition: time
        after: '09:00:00'
        before: '23:00:00'
    action:
      - service: switch.turn_on
        entity_id: switch.be_breezer_ptc

  - id: 'Выключить обогрев при нормальной температуре на улице днём'
    alias: be_breezer_disable_ptc_on_normal_temperature_day
    trigger:
      - platform: numeric_state
        entity_id: sensor.ha_outdoor_temperature
        above: 12
    condition:
      - condition: time
        after: '09:00:00'
        before: '23:00:00'
    action:
      - service: switch.turn_off
        entity_id: switch.be_breezer_ptc

  - id: 'Включить обогрев ночью при низкой температуре на улице и в комнате'
    alias: be_breezer_enable_ptc_on_low_temperature_night
    trigger:
      - platform: numeric_state
        entity_id: sensor.ha_outdoor_temperature
        below: 5
      - platform: numeric_state
        entity_id: sensor.be_temperature_temperature
        below: 19
    condition:
      - condition: time
        after: '23:00:00'
        before: '09:00:00'
      - condition: numeric_state
        entity_id: sensor.ha_outdoor_temperature
        below: 5
      - condition: numeric_state
        entity_id: sensor.be_temperature_temperature
        below: 19
    action:
      - service: switch.turn_on
        entity_id: switch.be_breezer_ptc

  - id: 'Выключить обогрев ночью при нормальной температуре на улице или в комнате'
    alias: be_breezer_disable_ptc_on_normal_temperature_night
    trigger:
      - platform: numeric_state
        entity_id: sensor.ha_outdoor_temperature
        above: 7
      - platform: numeric_state
        entity_id: sensor.be_temperature_temperature
        above: 20
      - platform: time_pattern
        hours: 23
        minutes: 00
    condition:
      - condition: time
        after: '23:00:00'
        before: '09:00:00'
      - condition: numeric_state
        entity_id: sensor.be_temperature_temperature
        above: 20
    action:
      - service: switch.turn_off
        entity_id: switch.be_breezer_ptc
