switch:
  - platform: template
    switches:
      be_breezer_ptc:
        friendly_name: Обогреватель бризера в спальне
        value_template: "{{ is_state_attr('fan.be_breezer_source', 'ptc', True) }}"
        turn_on:
          service: xiaomi_miio_airpurifier.fan_set_ptc_on
          data:
            entity_id: fan.be_breezer_source
        turn_off:
          service: xiaomi_miio_airpurifier.fan_set_ptc_off
          data:
            entity_id: fan.be_breezer_source
        icon_template: >-
          {% if is_state_attr('fan.be_breezer_source', 'ptc', true) %}
          mdi:radiator
          {% else %}
          mdi:radiator-disabled
          {% endif %}

sensor:
  - platform: template
    sensors:
      be_breezer_ntc_temperature:
        friendly_name: Температура обогревателя у бризера в спальне
        value_template: "{{ state_attr('fan.be_breezer_source', 'ntc_temperature') }}"
        icon_template: mdi:sun-thermometer
        unit_of_measurement: '°C'
      be_breezer_temperature:
        friendly_name: Температура по бризеру в спальне
        value_template: "{{ state_attr('fan.be_breezer_source', 'temperature') }}"
        icon_template: mdi:thermometer
        unit_of_measurement: '°C'

automation:
  - id: 'Включить обогрев по расписанию утром при низкой температуре на обогревателе и в комнате'
    alias: be_breezer_scheduled_enable_ptc_on_low_temperature_morning
    trigger:
      - platform: time_pattern
        hours: 07
        minutes: 00
    condition:
      - condition: numeric_state
        entity_id: sensor.be_breezer_ntc_temperature
        below: 15
      - condition: numeric_state
        entity_id: sensor.be_breezer_temperature
        below: 23
    action:
      - service: switch.turn_on
        entity_id: switch.be_breezer_ptc

  - id: 'Включить обогрев при низкой температуре на обогревателе и в комнате днём'
    alias: be_breezer_enable_ptc_on_low_temperature_day
    trigger:
      - platform: numeric_state
        entity_id: sensor.be_breezer_ntc_temperature
        below: 15
      - platform: numeric_state
        entity_id: sensor.be_breezer_temperature
        below: 23
    condition:
      - condition: numeric_state
        entity_id: sensor.be_breezer_ntc_temperature
        below: 15
      - condition: numeric_state
        entity_id: sensor.be_breezer_temperature
        below: 23
      - condition: time
        after: '07:00:00'
        before: '23:00:00'
    action:
      - service: switch.turn_on
        entity_id: switch.be_breezer_ptc

  - id: 'Выключить обогрев при нормальной температуре на обогревателе и в комнате днём'
    alias: be_breezer_disable_ptc_on_normal_temperature_day
    trigger:
      - platform: numeric_state
        entity_id: sensor.be_breezer_ntc_temperature
        above: 18
      - platform: numeric_state
        entity_id: sensor.be_breezer_temperature
        above: 23.5
    condition:
      - condition: numeric_state
        entity_id: sensor.be_breezer_ntc_temperature
        above: 18
      - condition: numeric_state
        entity_id: sensor.be_breezer_temperature
        above: 23.5
      - condition: time
        after: '07:00:00'
        before: '23:00:00'
    action:
      - service: switch.turn_off
        entity_id: switch.be_breezer_ptc

  - id: 'Выключить обогрев по расписанию вечером при нормальной температуре на обогревателе и в комнате'
    alias: be_breezer_scheduled_disable_ptc_on_normal_temperature_evening
    trigger:
      - platform: time_pattern
        hours: 23
        minutes: 00
    condition:
      - condition: numeric_state
        entity_id: sensor.be_breezer_ntc_temperature
        above: 18
      - condition: numeric_state
        entity_id: sensor.be_temperature_temperature
        above: 20
    action:
      - service: switch.turn_off
        entity_id: switch.be_breezer_ptc

  - id: 'Включить обогрев при низкой температуре на обогревателе и в комнате ночью'
    alias: be_breezer_enable_ptc_on_low_temperature_night
    trigger:
      - platform: numeric_state
        entity_id: sensor.be_breezer_ntc_temperature
        below: 15
      - platform: numeric_state
        entity_id: sensor.be_temperature_temperature
        below: 20
    condition:
      - condition: numeric_state
        entity_id: sensor.be_breezer_ntc_temperature
        below: 15
      - condition: numeric_state
        entity_id: sensor.be_temperature_temperature
        below: 20
      - condition: time
        after: '23:00:00'
        before: '07:00:00'
    action:
      - service: switch.turn_on
        entity_id: switch.be_breezer_ptc

  - id: 'Выключить обогрев при нормальной температуре на обогревателе и в комнате ночью'
    alias: be_breezer_disable_ptc_on_normal_temperature_night
    trigger:
      - platform: numeric_state
        entity_id: sensor.be_breezer_ntc_temperature
        above: 18
      - platform: numeric_state
        entity_id: sensor.be_temperature_temperature
        above: 21
    condition:
      - condition: numeric_state
        entity_id: sensor.be_breezer_ntc_temperature
        above: 18
      - condition: numeric_state
        entity_id: sensor.be_temperature_temperature
        above: 21
      - condition: time
        after: '23:00:00'
        before: '07:00:00'
    action:
      - service: switch.turn_off
        entity_id: switch.be_breezer_ptc
