- platform: template
  sensors:
    ba_normal_humidity:
      friendly_name: 'Нормальная влажность в ванной, не более, чем на 5% выше, чем в спальне'
      value_template: >-
        {{ (states("sensor.ba_humidity")|int - states("sensor.be_humidity")|int) <= 5 }}
    ba_high_humidity:
      friendly_name: 'Высокая влажность в ванной, больше 60% и более, чем на 10% выше, чем в спальне'
      value_template: >-
        {{ states("sensor.ba_humidity")|int >= 60 and (states("sensor.ba_humidity")|int - states("sensor.be_humidity")|int) >= 10 }}
    ba_very_high_humidity:
      friendly_name: 'Очень высокая влажность в ванной, выше 80%'
      value_template: >-
        {{ states("sensor.ba_humidity")|int >= 80 }}
