automation:
  - id: 'Уведомить о задымлении на кухне'
    alias: kn_alarm_on_smoke
    trigger:
      - platform: state
        entity_id: binary_sensor.kn_smoke_smoke
        to: 'on'
    action:
      - service: script.be_alarm_siren
        data:
          sls_name: 'SLSHubBE'
          device_name: 'BE_AlarmSiren'
          melody: 11
          duration: 5
      - service: script.notify_all
        data:
          message: |
            Задымление на кухне!!!
      - service: media_player.volume_set
        entity_id: media_player.be_yandex_station
        data:
          volume_level: 0.8
      - service: media_player.play_media
        entity_id: media_player.be_yandex_station
        data:
          media_content_id: 'Внимание! На кухне что-то горит! Надо бы проверить, как бы чего не случилось!'
          media_content_type: text
      - delay: 0:00:07
      - service: media_player.volume_set
        entity_id: media_player.be_yandex_station
        data:
          volume_level: 0.3
