homeassistant:
  customize:
    light.slshubli_led:
      friendly_name: 'Ночник в гостиной'

mqtt:
  switch:
    - name: li_sls_join
      state_topic: 'SLSHubLI/bridge/config/permit_join'
      command_topic: 'SLSHubLI/bridge/config/permit_join'
      payload_on: 'true'
      payload_off: 'false'

  sensor:
    - name: li_sls_version
      state_topic: 'SLSHubLI/bridge/config'
      value_template: '{{ value_json.Version }}'

  binary_sensor:
    - name: li_sls_state
      state_topic: 'SLSHubLI/bridge/state'
      payload_on: 'online'
      payload_off: 'offline'
