homeassistant:
  customize:
    light.slshubch_led:
      friendly_name: 'Ночник в детской'

mqtt:
  switch:
    - name: ch_sls_join
      state_topic: 'SLSHubCH/bridge/config/permit_join'
      command_topic: 'SLSHubCH/bridge/config/permit_join'
      payload_on: 'true'
      payload_off: 'false'

  sensor:
    - name: ch_sls_version
      state_topic: 'SLSHubCH/bridge/config'
      value_template: '{{ value_json.Version }}'

  binary_sensor:
    - name: ch_sls_state
      state_topic: 'SLSHubCH/bridge/state'
      payload_on: 'online'
      payload_off: 'offline'
