telegram_bot:
  - platform: polling
    api_key: !secret telegram_token
    allowed_chat_ids:
      - !secret telegram_alexey
      - !secret telegram_julia
      - !secret telegram_dana

notify:
  - name: julia
    platform: telegram
    chat_id: !secret telegram_julia
  - name: alexey
    platform: telegram
    chat_id: !secret telegram_alexey
  - name: dana
    platform: telegram
    chat_id: !secret telegram_dana

group:
  unavailable_lights:
    name: unavailable_sensors
    entities: []
  unavailable_switches:
    name: unavailable_sensors
    entities: []
  unavailable_sensors:
    name: unavailable_sensors
    entities: []
  unavailable_bin_sensors:
    name: unavailable_sensors
    entities: []

sensor:
  - platform: template
    sensors:
      unavailable_lights_count:
        friendly_name: 'Всего недоступных светильников'
        value_template: '{{ expand("group.unavailable_lights") | list | count }}'
        icon_template: mdi:counter

      unavailable_switches_count:
        friendly_name: 'Всего недоступных выключателей'
        value_template: '{{ expand("group.unavailable_switches") | list | count }}'
        icon_template: mdi:counter

      unavailable_sensors_count:
        friendly_name: 'Всего недоступных сенсоров - '
        value_template: '{{ expand("group.unavailable_sensors") | list | count }}'
        icon_template: mdi:counter

      unavailable_bin_sensors_count:
        friendly_name: 'Всего недоступных бинарных сенсоров - '
        value_template: '{{ expand("group.unavailable_bin_sensors") | list | count }}'
        icon_template: mdi:counter

script:
  system_report:
    description: 'Отправка отчета о состоянии системы'
    sequence:
      - service: group.set
        data:
          object_id: unavailable_lights
          entities: >
            {{ states.light | selectattr ("state", "equalto", "unavailable") | map(attribute="entity_id") | list }}
      - service: group.set
        data:
          object_id: unavailable_switches
          entities: >
            {{ states.switch | selectattr ("state", "equalto", "unavailable") | map(attribute="entity_id") | list }}
      - service: group.set
        data:
          object_id: unavailable_sensors
          entities: >
            {{ states.sensor | selectattr ("state", "equalto", "unavailable") | map(attribute="entity_id") | list }}
      - service: group.set
        data:
          object_id: unavailable_bin_sensors
          entities: >
            {{ states.binary_sensor | selectattr ("state", "equalto", "unavailable") | map(attribute="entity_id") | list }}
      - service: notify.alexey
        data:
          message: "
            {{'🧠'}} Состояние системы\n\
            {{'🗓'}} Отчет за {{ states('sensor.time_date') }}\n\
            {{'💡'}} Светильников недоступно - {{ states('sensor.unavailable_lights_count') }}\n\
            {% if states('sensor.unavailable_lights_count') | float > 0 %}{% for object in expand('group.unavailable_lights') %}    {{object.entity_id | replace('_', '\\_') }}\n{% endfor %}{% endif %}\
            {{'🎚'}} Выключателей недоступно - {{ states('sensor.unavailable_switches_count') }}\n\
            {% if states('sensor.unavailable_switches_count') | float > 0 %}{% for object in expand('group.unavailable_switches') %}    {{ object.entity_id | replace('_', '\\_') }}\n{% endfor %}{% endif %}\
            {{'🌡'}} Сенсоров недоступно - {{ states('sensor.unavailable_sensors_count') }}\n\
            {% if states('sensor.unavailable_sensors_count') | float > 0 %}{% for object in expand('group.unavailable_sensors') %}    {{object.entity_id | replace('_', '\\_')}}\n{% endfor %}{% endif %}\
            {{'🖲'}} Бинарных сенсоров недоступно - {{ states('sensor.unavailable_bin_sensors_count') }}\n\
            {% if states('sensor.unavailable_bin_sensors_count') | float > 0 %}{% for object in expand('group.unavailable_bin_sensors') %}    {{ object.entity_id | replace('_', '\\_') }}\n{% endfor %}{% endif %}\
            "

  notify_all:
    description: 'Уведомление всем'
    fields:
      message:
        description: 'Сообщение'
        example: 'Сообщение'
    sequence:
      - service: notify.alexey
        data:
          message: '{{ message }}'
      - service: notify.julia
        data:
          message: '{{ message }}'
      - service: notify.dana
        data:
          message: '{{ message }}'

automation:
  - id: 'Отчет при запуске системы'
    alias: system_start_message
    initial_state: true
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: notify.alexey
        data:
          message: |
            {{'\U0001F4AC'}} Основной сервер Raspberry Pi
            {{'\U0001F567'}} Запуск в {{ states('sensor.time_date') }}
            {{'\U0001F4C3'}} Отчет о состоянии будет через 1 минуту
      - delay: '00:01:00'
      - service: script.system_report
