vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token

input_boolean:
  daily_vacuum_first_run:
    name: Daily Vacuum First Run
    initial: off
  disable_daily_vacuum:
    name: 'Выключить автоматизацию ежедневной уборки'
    initial: on
  disable_dustbin_notification:
    name: 'Отключить уведомление об очистке мусорного контейнера'
    initial: off

input_select:
  vacuum_room:
    name: Выберите комнату
    options:
      - Ничего не выбрано
      - Вся квартира
      - Коридор
      - Кухня
      - Спальня
      - Детская
      - Гостиная
      - Туалет
      - Кабинет
  vacuum_fan_speed_list:
    name: Мощность всасывания
    options:
      - Silent
      - Standard
      - Medium
      - Turbo

sensor:
  - platform: template
    sensors:
      vacuum_status:
        friendly_name: 'Статус'
        value_template: '{{ state_attr("vacuum.xiaomi_vacuum_cleaner", "status") }}'
        icon_template: >
          {% set val =  state_attr('vacuum.xiaomi_vacuum_cleaner', 'status')  %}
          {% if val == 'Charging' %}
            mdi:battery-charging
          {% elif val == 'Cleaning' %}
            mdi:move-resize
          {% elif val == 'Returning home' %}
            mdi:keyboard-return
          {% elif val == 'Idle' %}
            mdi:dots-horizontal
          {% elif val == 'Paused' %}
            mdi:pause-circle
          {% else %}
            mdi:help-circle
          {% endif %}
      vacuum_battery:
        friendly_name: 'Заряд батареи'
        value_template: '{{ state_attr("vacuum.xiaomi_vacuum_cleaner", "battery_level") }}'
        unit_of_measurement: '%'
        icon_template: '{{ state_attr("vacuum.xiaomi_vacuum_cleaner", "battery_icon") }}'
      vacuum_cleaning_time:
        friendly_name: 'Последняя уборка'
        value_template: '{{ state_attr("vacuum.xiaomi_vacuum_cleaner", "cleaning_time") }}'
        icon_template: 'mdi:timer'
      vacuum_cleaned_area:
        friendly_name: 'Площадь'
        unit_of_measurement: 'м²'
        value_template: '{{ state_attr("vacuum.xiaomi_vacuum_cleaner", "cleaned_area") }}'
        icon_template: 'mdi:ruler'


script:
  vacuum_start:
    description: 'Пропылесосить квартиру'
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - service: script.notify_all
        data:
          message: |
            Пылесос приступил к уборке всей квартиры

  vacuum_start_notify_door:
    description: 'Уведомление о начале уборки квартиры'
    sequence:
      - service: script.notify_all
        data:
          message: |
            Пылесос начнёт убираться через 10 минут.
            Откройте двери и уберите барахло с пола.

  be_vacuum_clean:
    description: 'Пропылесосить спальню'
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [ [ 22504,18211,25554,25111,1 ] ]
      - service: script.notify_all
        data:
          message: |
            Пылесос приступил к уборке в cпальне

  ch_vacuum_clean:
    description: 'Пропылесосить детскую'
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [ [ 22528,27088,26328,31088,1 ] ]
      - service: script.notify_all
        data:
          message: |
            Пылесос приступил к уборке в детской

  li_vacuum_clean:
    description: 'Пропылесосить гостиную'
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [ [ 26431,26949,32031,31349,1 ] ]
      - service: script.notify_all
        data:
          message: |
            Пылесос приступил к уборке в гостиной

  ki_vacuum_clean:
    description: 'Пропылесосить кухню'
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [ [ 32663,27125,37363,30325,1 ] ]
      - service: script.notify_all
        data:
          message: |
            Пылесос приступил к уборке на кухне

  co_vacuum_clean:
    description: 'Пропылесосить коридор'
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [ [ 25578,23783,35628,27083,1 ],[ 24647,25083,25847,27133,1 ] ]
      - service: script.notify_all
        data:
          message: |
            Пылесос приступил к уборке в коридоре

  to_vacuum_clean:
    description: 'Пропылесосить туалет'
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [ [ 34023,25341,35573,26991,1 ] ]
      - service: script.notify_all
        data:
          message: |
            Пылесос приступил к уборке в туалете

  ca_vacuum_clean:
    description: 'Пропылесосить кабинет'
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [ [ 22554,18248,25354,20048,1 ] ]
      - service: script.notify_all
        data:
          message: |
            Пылесос приступил к уборке в кабинете

automation:
  - id: 'Выставление режима всасывания пылесоса'
    alias: vacuum_set_fan_mode
    trigger:
      platform: state
      entity_id: input_select.vacuum_fan_speed_list
    action:
      - service: vacuum.set_fan_speed
        data_template:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          fan_speed: "{{ states('input_select.vacuum_fan_speed_list') }}"

  - id: 'Обновление состояния для селекта режима всасывания пылесоса'
    alias: vacuum_update_input_select_fan_mode
    initial_state: true
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: sensor.vacuum_fan_speed
    condition:
      condition: template
      value_template: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'fan_speed') != states('input_select.vacuum_fan_speed_list') }}"
    action:
      - service: input_select.select_option
        entity_id: input_select.vacuum_fan_speed_list
        data_template:
          option: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'fan_speed') }}"

  - id: 'Начать уборку комнаты'
    alias: vacuum_start_cleaning_room
    trigger:
      - platform: state
        entity_id: input_select.vacuum_room
        from: 'Ничего не выбрано'
    action:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state('input_select.vacuum_room', 'Вся квартира') %}
              script.vacuum_start
            {% elif is_state('input_select.vacuum_room', 'Коридор') %}
              script.co_vacuum_clean
            {% elif is_state('input_select.vacuum_room', 'Кухня') %}
              script.kn_vacuum_clean
            {% elif is_state('input_select.vacuum_room', 'Гостиная') %}
              script.li_vacuum_clean
            {% elif is_state('input_select.vacuum_room', 'Детская') %}
              script.ch_vacuum_clean
            {% elif is_state('input_select.vacuum_room', 'Спальня') %}
              script.be_vacuum_clean
            {% elif is_state('input_select.vacuum_room', 'Туалет') %}
              script.to_vacuum_clean
            {% elif is_state('input_select.vacuum_room', 'Кабинет') %}
              script.ca_vacuum_clean
            {% else %}
            {% endif %}
      - service: vacuum.set_fan_speed
        data_template:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          fan_speed: 'Turbo'
      - service: input_select.select_option
        entity_id: input_select.vacuum_room
        data_template:
          option: 'Ничего не выбрано'

  - id: 'Робот пылесос закончил уборку'
    alias: vacuum_finished_cleaning
    trigger:
      - platform: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        from: 'cleaning'
        to: 'returning'
    action:
      - service: vacuum.set_fan_speed
        data_template:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          fan_speed: 'Silent'
      - service: script.notify_all
        data:
          message: |
            Пылесос закончил уборку
      - service: notify.dana
        data:
          message: |
            Вытряхни Шурика... ну пазязя... {{'\U0001F64F'}}

  - id: 'Уведомление об ошибке'
    alias: vacuum_error_notification
    trigger:
      - platform: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        to: 'error'
    action:
      - service: script.notify_all
        data:
          message: |
            Робот пылесос ошибка {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'error') }}

  - id: 'Уведомление об уборке'
    alias: vacuum_scheduled_start_notification
    trigger:
      - platform: time_pattern
        hours: 21
        minutes: 50
    action:
      - service: script.notify_all
        data:
          message: |
            Пылесос начнёт убираться через 10 минут.
            Откройте двери и уберите барахло с пола.

  - id: 'Уведомление о закрытых дверях'
    alias: vacuum_scheduled_start_notification_door
    trigger:
      - platform: time_pattern
        hours: 21
        minutes: 55
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.be_door_contact
          state: 'off'
        - condition: state
          entity_id: binary_sensor.ch_door_contact
          state: 'off'
        - condition: state
          entity_id: binary_sensor.li_door_contact
          state: 'off'
        - condition: state
          entity_id: binary_sensor.kn_door_contact
          state: 'off'
    action:
      - service: script.notify_all
        data:
          message: >
            Всё ещё закрыты двери:
              {% if is_state('binary_sensor.be_door_contact', 'off') %}- спальня {% endif %}
              {% if is_state('binary_sensor.ch_door_contact', 'off') %}- детская {% endif %}
              {% if is_state('binary_sensor.li_door_contact', 'off') %}- гостиная {% endif %}
              {% if is_state('binary_sensor.kn_door_contact', 'off') %}- кухня{% endif %}
            Откройте пазязя, ну пазязя... {{'\U0001F64F'}}

  - id: 'Старт уборки по расписанию'
    alias: vacuum_scheduled_start
    trigger:
      - platform: time_pattern
        hours: 22
    action:
      - service: vacuum.set_fan_speed
        data_template:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          fan_speed: 'Turbo'
      - service: script.vacuum_start
