- platform: generic_thermostat
  name: li_radiator
  heater: switch.li_boiler_channel
  target_sensor: sensor.li_temperature_temperature
  min_temp: 15
  max_temp: 30
  target_temp: 24
  min_cycle_duration: '00:30:00'
  cold_tolerance: 0.2
  hot_tolerance: 0.2
  away_temp: 19
  precision: 0.5
  initial_hvac_mode: 'off'
