- platform: generic_thermostat
  name: be_radiator
  heater: switch.be_boiler_channel
  target_sensor: sensor.be_temperature
  min_temp: 15
  max_temp: 30
  target_temp: 24
  min_cycle_duration: '00:15:00'
  cold_tolerance: 0.2
  hot_tolerance: 0.2
  away_temp: 19
  precision: 0.5
  initial_hvac_mode: 'off'

- platform: generic_thermostat
  name: ch_radiator
  heater: switch.ch_boiler_channel
  target_sensor: sensor.ch_temperature
  min_temp: 15
  max_temp: 30
  target_temp: 24
  min_cycle_duration: '00:15:00'
  cold_tolerance: 0.2
  hot_tolerance: 0.2
  away_temp: 19
  precision: 0.5
  initial_hvac_mode: 'off'

- platform: generic_thermostat
  name: li_radiator
  heater: switch.li_boiler_channel
  target_sensor: sensor.li_temperature
  min_temp: 15
  max_temp: 30
  target_temp: 24
  min_cycle_duration: '00:15:00'
  cold_tolerance: 0.2
  hot_tolerance: 0.2
  away_temp: 19
  precision: 0.5
  initial_hvac_mode: 'off'
